version: '3.8'

services:
    nginx:
        build: ./requirements/nginx
        ports:
            - "443:443"
            - "80:80"
        volumes:
            - nginx-data:/var/www/html
        container_name: nginx
        depends_on:
            - wordpress
        restart: always
        networks:
            - internal
    wordpress:
        build: ./requirements/wordpress
        container_name: wordpress
        volumes:
            - wordpress-data:/var/www/html
        depends_on:
            - mariadb
        networks:
            - internal
        restart: always
        env_file:
            - .env
    mariadb:
        build: ./requirements/mariadb
        container_name: mariadb
        volumes:
            - mariadb-data:/var/lib/mysql/
        env_file:
            - .env
        restart: always
        networks:
            - internal
    redis:
        build: ./requirements/redis
        container_name: redis
        restart: always
        networks:
            - internal
    ftp:
        build:
            context: ./requirements/ftp
            args:
                FTP_USER: ${FTP_USER}
                FTP_USER_PASSWORD: ${FTP_USER_PASSWORD}
        ports:
            - "2121:21"
            - "20:20"
            - "50000-50010:50000-50010"
        env_file:
            - .env
        volumes:
            - ftp-data:/home/achahid-/ftp/wordpress
        restart: always
        networks:
            - internal
    adminer:
        build: ./requirements/adminer
        container_name: adminer
        volumes:
            - adminer-data:/var/www/html
        restart: always
        networks:
            - internal
    duplicati:
        build: ./requirements/duplicati
        container_name: duplicati
        volumes:
            - ./backups:/backups
            - ./config:/config
            - /:/source
        env_file:
            - .env
        environment:
             - TZ=Etc/UTC
        restart: always
        ports:
            - "8200:8200"
        networks:
            - internal

networks:
    internal:
        driver: bridge

volumes:
    nginx-data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/achahid-/data/web
    wordpress-data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/achahid-/data/web
    mariadb-data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/achahid-/data/database
    ftp-data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/achahid-/data/web
    adminer-data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/achahid-/data/web
