version: '3.8'

services:
    nginx:
        build: ./requirements/nginx
        ports:
            - "443:443"
        volumes:
            - ./requirements/web:/var/www/html
        container_name: nginx
        networks:
            - internal
    wordpress:
        build: ./requirements/wordpress
        container_name: wordpress
        volumes:
            - ./requirements/web:/var/www/html
        networks:
            - internal

networks:
    internal:
        driver: bridge
