version: '3.8'

services:
    nginx:
        build: ./requirements/nginx
        ports:
            - "443:443"
        volumes:
            - ./requirements/web:/var/www/html
        container_name: nginx
        depends_on:
            - wordpress
        networks:
            - internal
    wordpress:
        build: ./requirements/wordpress
        container_name: wordpress
        volumes:
            - ./requirements/web:/var/www/html
        depends_on:
            - mariadb
        networks:
            - internal
    mariadb:
        build: ./requirements/mariadb
        container_name: mariadb
        # volumes:
        #     - ./database:/var/lib/mysql
        networks:
            - internal

networks:
    internal:
        driver: bridge
