version: '3.8'

services:
    nginx:
        build: ./requirements/nginx
        ports:
            - "443:443"
        volumes:
            - ./requirements/web:/var/www/html
        container_name: nginx
        depends_on:
            - wordpress
        restart: always
        networks:
            - internal
    wordpress:
        build: ./requirements/wordpress
        container_name: wordpress
        volumes:
            - ./requirements/web:/var/www/html
        depends_on:
            - mariadb
        networks:
            - internal
        restart: always
        env_file:
            - .env
    mariadb:
        build: ./requirements/mariadb
        container_name: mariadb
        volumes:
            - ./database:/var/lib/mysql/
        env_file:
            - .env
        restart: always
        networks:
            - internal
    redis:
        build: ./requirements/redis
        container_name: redis
        restart: always
        networks:
            - internal

networks:
    internal:
        driver: bridge

volumes:
    database:
        driver: local
    web:
        driver: local
