FROM debian:bullseye

# install mariadb
RUN apt-get update && \
    apt-get install -y mariadb-server && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Configure mariadb
COPY ./config/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf
COPY ./tools/init.sql /etc/mysql/init.sql

COPY ./tools/script.sh /usr/bin/script.sh
RUN chmod +x /usr/bin/script.sh

EXPOSE 3306

ENTRYPOINT ["/usr/bin/script.sh"]
