FROM debian:bullseye

RUN apt-get update && \
	apt-get install -y wget php && \
	mkdir -p /var/www/html && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/*

COPY ./tools/start.sh /usr/bin/start.sh

RUN chmod +x /usr/bin/start.sh

EXPOSE 8080

CMD ["usr/bin/start.sh"]
