FROM debian:bullseye

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
        wget \
        mono-runtime \
        ca-certificates \
        libice6 libsm6 libfontconfig1 libicu-dev || \
        (echo "Failed to install dependencies" && apt-get install -f -y) && \
        apt-get clean && \
        rm -rf /var/lib/apt/lists/*

# Download and install Duplicati
RUN wget https://updates.duplicati.com/stable/duplicati-2.1.0.5_stable_2025-03-04-linux-x64-gui.deb -O duplicati.deb && \
    dpkg -i duplicati.deb && \ 
    rm duplicati.deb

COPY ./tools/start.sh /usr/bin/start.sh
RUN chmod +x /usr/bin/start.sh

EXPOSE 8200

ENTRYPOINT ["/usr/bin/start.sh"]

# NOTE: duplicati needs an amd64 architecture to run properly.
# because of dpkg -i duplicati.deb
# If you are using a different architecture, you may need to build Duplicati from source or use a different image.
# For more information, visit https://duplicati.com/
