FROM debian:bullseye

# install php
RUN apt-get update && \
    apt-get install -y php-fpm php7.4-fpm && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir -p /run/php && \
    echo "listen = 9000" >> /etc/php/7.4/fpm/pool.d/www.conf

EXPOSE 9000

CMD ["php-fpm7.4", "-F"]
