FROM debian:bullseye

# install redis
RUN apt-get update && \
	apt-get install -y redis-server redis-tools && \
	# Clean unecessary stuffs, optimize image weight.
	apt-get clean && \
	rm -rf /var/lib/apt/lists/*

# Configure redis
COPY ./config/redis.conf /etc/redis/redis.conf

EXPOSE 6379
	
# run redis server in foreground
CMD ["redis-server", "--protected-mode", "no"]
