FROM debian:bullseye

RUN apt-get update && \
    apt-get install -y nginx openssl && \
    # Clean unecessary stuffs, optimize image weight.
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /etc/nginx/ssl/private && \
    mkdir -p /etc/nginx/ssl/certs

RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/nginx/ssl/private/nginx-selfsigned_ks.key \
    -out /etc/nginx/ssl/certs/nginx-selfsigned_ks.crt \
    -subj "/C=MA/ST=Benguerir/L=Benguerir/O=1337/CN=achahid-.42.fr" && \
    chmod 600 /etc/nginx/ssl/private/nginx-selfsigned_ks.key

COPY ./config/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 443
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
